// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID          uuid.UUID          `json:"id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID        int64              `json:"id"`
	SeasonID  int64              `json:"season_id"`
	PlayerID  uuid.UUID          `json:"player_id"`
	Decisions []byte             `json:"decisions"`
	Points    int32              `json:"points"`
	Wins      int32              `json:"wins"`
	Podiums   int32              `json:"podiums"`
	Dnfs      int32              `json:"dnfs"`
	Result    []byte             `json:"result"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Season struct {
	ID         int64              `json:"id"`
	Seed       int64              `json:"seed"`
	SimVersion string             `json:"sim_version"`
	Calendar   []byte             `json:"calendar"`
	Field      []byte             `json:"field"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
