// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRuns = `-- name: CountRuns :one
SELECT count(*) FROM runs
`

func (q *Queries) CountRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunsForPlayer = `-- name: CountRunsForPlayer :one
SELECT count(*) FROM runs WHERE player_id = $1
`

func (q *Queries) CountRunsForPlayer(ctx context.Context, playerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsForPlayer, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (season_id, player_id, decisions, points, wins, podiums, dnfs, result)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, season_id, player_id, decisions, points, wins, podiums, dnfs, result, created_at
`

type CreateRunParams struct {
	SeasonID  int64     `json:"season_id"`
	PlayerID  uuid.UUID `json:"player_id"`
	Decisions []byte    `json:"decisions"`
	Points    int32     `json:"points"`
	Wins      int32     `json:"wins"`
	Podiums   int32     `json:"podiums"`
	Dnfs      int32     `json:"dnfs"`
	Result    []byte    `json:"result"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.SeasonID,
		arg.PlayerID,
		arg.Decisions,
		arg.Points,
		arg.Wins,
		arg.Podiums,
		arg.Dnfs,
		arg.Result,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.PlayerID,
		&i.Decisions,
		&i.Points,
		&i.Wins,
		&i.Podiums,
		&i.Dnfs,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (seed, sim_version, calendar, field)
VALUES ($1, $2, $3, $4)
RETURNING id, seed, sim_version, calendar, field, created_at
`

type CreateSeasonParams struct {
	Seed       int64  `json:"seed"`
	SimVersion string `json:"sim_version"`
	Calendar   []byte `json:"calendar"`
	Field      []byte `json:"field"`
}

// One row per issued run. There is no conflict to handle any more: every
// call mints a new season, which is what unlimited play means.
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.Seed,
		arg.SimVersion,
		arg.Calendar,
		arg.Field,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.SimVersion,
		&i.Calendar,
		&i.Field,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT b.player_id, b.points, b.wins, b.podiums, b.dnfs, b.created_at, b.runs, p.display_name
FROM (
  SELECT DISTINCT ON (player_id)
         player_id, points, wins, podiums, dnfs, created_at,
         count(*) OVER (PARTITION BY player_id) AS runs
  FROM runs
  ORDER BY player_id, points DESC, wins DESC, podiums DESC, created_at ASC
) b
JOIN players p ON p.id = b.player_id
ORDER BY b.points DESC, b.wins DESC, b.podiums DESC, b.created_at ASC
LIMIT $1 OFFSET $2
`

type GetLeaderboardParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetLeaderboardRow struct {
	PlayerID    uuid.UUID          `json:"player_id"`
	Points      int32              `json:"points"`
	Wins        int32              `json:"wins"`
	Podiums     int32              `json:"podiums"`
	Dnfs        int32              `json:"dnfs"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Runs        int64              `json:"runs"`
	DisplayName string             `json:"display_name"`
}

// All-time, one row per player: their best season, plus how many they have
// submitted. The run count is not decoration -- when play is unlimited a
// best-of-N is partly a measure of N, and showing it is the honest way to
// present that rather than pretending otherwise.
//
// DISTINCT ON needs its own ordering to pick the best row per player, so
// the outer query re-sorts into leaderboard order.
func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Points,
			&i.Wins,
			&i.Podiums,
			&i.Dnfs,
			&i.CreatedAt,
			&i.Runs,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunForPlayer = `-- name: GetRunForPlayer :one
SELECT id, season_id, player_id, decisions, points, wins, podiums, dnfs, result, created_at FROM runs WHERE season_id = $1 AND player_id = $2
`

type GetRunForPlayerParams struct {
	SeasonID int64     `json:"season_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) GetRunForPlayer(ctx context.Context, arg GetRunForPlayerParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForPlayer, arg.SeasonID, arg.PlayerID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.PlayerID,
		&i.Decisions,
		&i.Points,
		&i.Wins,
		&i.Podiums,
		&i.Dnfs,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, seed, sim_version, calendar, field, created_at FROM seasons WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.SimVersion,
		&i.Calendar,
		&i.Field,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPlayer = `-- name: UpsertPlayer :one
INSERT INTO players (id, display_name) VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name
RETURNING id, display_name, created_at
`

type UpsertPlayerParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, upsertPlayer, arg.ID, arg.DisplayName)
	var i Player
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}
