// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRuns = `-- name: CountRuns :one
SELECT count(*) FROM runs WHERE season_id = $1
`

func (q *Queries) CountRuns(ctx context.Context, seasonID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRuns, seasonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (season_id, player_id, decisions, points, wins, podiums, dnfs, result)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, season_id, player_id, decisions, points, wins, podiums, dnfs, result, created_at
`

type CreateRunParams struct {
	SeasonID  int64     `json:"season_id"`
	PlayerID  uuid.UUID `json:"player_id"`
	Decisions []byte    `json:"decisions"`
	Points    int32     `json:"points"`
	Wins      int32     `json:"wins"`
	Podiums   int32     `json:"podiums"`
	Dnfs      int32     `json:"dnfs"`
	Result    []byte    `json:"result"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.SeasonID,
		arg.PlayerID,
		arg.Decisions,
		arg.Points,
		arg.Wins,
		arg.Podiums,
		arg.Dnfs,
		arg.Result,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.PlayerID,
		&i.Decisions,
		&i.Points,
		&i.Wins,
		&i.Podiums,
		&i.Dnfs,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (seed, sim_version, calendar, field, published_at, closes_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (published_at) DO NOTHING
RETURNING id, seed, sim_version, calendar, field, published_at, closes_at
`

type CreateSeasonParams struct {
	Seed        int64              `json:"seed"`
	SimVersion  string             `json:"sim_version"`
	Calendar    []byte             `json:"calendar"`
	Field       []byte             `json:"field"`
	PublishedAt pgtype.Date        `json:"published_at"`
	ClosesAt    pgtype.Timestamptz `json:"closes_at"`
}

// ON CONFLICT DO NOTHING is what makes the daily scheduler idempotent and
// safe to run on several instances without leader election. It returns NO
// ROW on conflict, so the caller must fall back to re-reading.
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.Seed,
		arg.SimVersion,
		arg.Calendar,
		arg.Field,
		arg.PublishedAt,
		arg.ClosesAt,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.SimVersion,
		&i.Calendar,
		&i.Field,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT r.player_id, r.points, r.wins, r.podiums, r.dnfs, r.created_at, p.display_name
FROM runs r
JOIN players p ON p.id = r.player_id
WHERE r.season_id = $1
ORDER BY r.points DESC, r.wins DESC, r.podiums DESC, r.created_at ASC
LIMIT $2 OFFSET $3
`

type GetLeaderboardParams struct {
	SeasonID int64 `json:"season_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type GetLeaderboardRow struct {
	PlayerID    uuid.UUID          `json:"player_id"`
	Points      int32              `json:"points"`
	Wins        int32              `json:"wins"`
	Podiums     int32              `json:"podiums"`
	Dnfs        int32              `json:"dnfs"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName string             `json:"display_name"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.SeasonID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Points,
			&i.Wins,
			&i.Podiums,
			&i.Dnfs,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunForPlayer = `-- name: GetRunForPlayer :one
SELECT id, season_id, player_id, decisions, points, wins, podiums, dnfs, result, created_at FROM runs WHERE season_id = $1 AND player_id = $2
`

type GetRunForPlayerParams struct {
	SeasonID int64     `json:"season_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) GetRunForPlayer(ctx context.Context, arg GetRunForPlayerParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForPlayer, arg.SeasonID, arg.PlayerID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.PlayerID,
		&i.Decisions,
		&i.Points,
		&i.Wins,
		&i.Podiums,
		&i.Dnfs,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getSeasonByDate = `-- name: GetSeasonByDate :one
SELECT id, seed, sim_version, calendar, field, published_at, closes_at FROM seasons WHERE published_at = $1
`

func (q *Queries) GetSeasonByDate(ctx context.Context, publishedAt pgtype.Date) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByDate, publishedAt)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.SimVersion,
		&i.Calendar,
		&i.Field,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, seed, sim_version, calendar, field, published_at, closes_at FROM seasons WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.SimVersion,
		&i.Calendar,
		&i.Field,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const upsertPlayer = `-- name: UpsertPlayer :one
INSERT INTO players (id, display_name) VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name
RETURNING id, display_name, created_at
`

type UpsertPlayerParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, upsertPlayer, arg.ID, arg.DisplayName)
	var i Player
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}
